### ISSUE TITLE
unexpected end of input reached

### ISSUE THREAD

**Issue by binarious** [containers/aardvark-dns#151]
I've setup a nextcloud deployment with podman in combination with docker-compose. It's working fine mostly and dns is also generally working. But around every 30s I see connection issues between containers. I've created a test script which queries the database every second and I often see connection errors (`SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again`). `journalctl` shows the following output at these times:
```
aardvark-dns[70887]: Failed while parsing message: unexpected end of input reached
aardvark-dns[70887]: None received while parsing dns message, this is not expected server will ignore this message
```

Any ideas?

<details>
  <summary>Deployment Setup</summary>

**System details**
- Fedora 36
- Podman 4.1.0
- Docker Compose 2.6.0
  
**podman**
```
systemctl --user enable podman.socket
systemctl --user start podman.socket
sudo dnf install -y podman podman-plugins
podman network create nginx-proxy
docker-compose up
```

**docker-compose.yml**
It's `app` which sometimes cannot connect to `db` and `redis`.

```yml
version: '3'

services:
  db:
    image: docker.io/library/mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: docker.io/library/redis:7.0-alpine
    restart: always

  app:
    image: docker.io/library/nextcloud:24-fpm-alpine
    restart: always
    security_opt:
      - label=disable
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    security_opt:
      - label=disable
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    ports:
      - "8082:8080"
    environment:
      VIRTUAL_HOST: REDACTED
      LETSENCRYPT_HOST: REDACTED
      LETSENCRYPT_EMAIL: REDACTED

  cron:
    image: docker.io/library/nextcloud:24-fpm-alpine
    restart: always
    security_opt:
      - label=disable
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/volumes/nextcloud"
  db:

networks:
  default:
    name: nginx-proxy
    external: true
```
</details>
