### ISSUE TITLE
re-enable make validate in CI

### ISSUE THREAD

**Issue by baude** [containers/aardvark-dns#60]
somehow the validate task dropped the make validate step.  Make validate yields a ton of things to correct.  Once corrected, edit the .cirrius.yaml and add make validate as a task to validate

**Comment by cevich** [comment]
It's there now, but it fails (and I'm not knowledgeable enough to fix it) so I did:

```yaml
validate_task:
  ...cut...
  # FIXME: At the time this task was added, the code currently does not
  # pass verification.  Somebody with rust skills should fix this, then
  # remove the following line:
  allow_failures: $CI == $CI
```

So somebody just needs to remove those lines in a PR, then start fixing the things it finds broken in the code.
